include:
  - path:
    - compose/caddy.yaml
    - compose/glance.yaml
    - compose/homeassistant.yaml
    - compose/qbittorrent.yaml
    - compose/vaultwarden.yaml
    - compose/syncthing.yaml

networks:
  appnet:
    driver: bridge
