include:
  - path:
    - docker/caddy.yaml
    - docker/glance.yaml
    - docker/homeassistant.yaml
    - docker/qbittorrent.yaml
    - docker/vaultwarden.yaml
    - docker/syncthing.yaml

networks:
  appnet:
    driver: bridge
