services:
  actual:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    restart: unless-stopped
    volumes:
      - /srv/actual:/data

  actual-inserter:
    build: /home-server/actual-inserter
    container_name: actual-inserter
    restart: unless-stopped
    depends_on:
      - actual
    environment:
      - ACTUAL_URL=http://actual:5006
      - ACTUAL_PASSWORD=${ACTUAL_PASSWORD}
      - ACTUAL_BUDGET_ID=${ACTUAL_BUDGET_ID}
      - ACTUAL_ACCOUNT_ID=${ACTUAL_ACCOUNT_ID}
    volumes:
      - /srv/actual-inserter:/data
      - /home-server/actual-inserter:/usr/src/app 
