services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /srv/caddy:/etc/caddy
      - /srv/caddy/data:/data
      - /srv/caddy/config:/config
    networks:
      - default
      - appnet
