services:
  dumbpad:
    image: dumbwareio/dumbpad:latest
    container_name: dumbpad
    restart: unless-stopped
    volumes:
      - /srv/dumbpad:/app/data
    environment:
      SITE_TITLE: DumbPad
      BASE_URL: https://dumbpad.home
