services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /srv/glance/config:/app/config
      - /srv/glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - appnet