services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=Etc/UTC
    volumes:
      - /srv/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - "${ZIGBEE_DEVICE:?Set ZIGBEE_DEVICE in .env}:/dev/ttyUSB-Zigbee"

  # esphome:
  #   image: ghcr.io/esphome/esphome
  #   container_name: esphome
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - /srv/esphome:/config

      