services:
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - postgresql
      - nc-redis
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_NC_PASSWORD}
      - REDIS_HOST=nc-redis
    volumes:
      - /srv/nextcloud/html:/var/www/html
      - /srv/nextcloud/config:/var/www/html/config
      - /srv/nextcloud/custom_apps:/var/www/html/custom_apps
      - /srv/nextcloud/data:/var/www/html/data
      - /srv/nextcloud/themes:/var/www/html/themes
    networks: [appnet]

  nc-redis:
    image: redis:7
    container_name: nc-redis
    restart: unless-stopped
    volumes:
      - /srv/redis:/data
    networks: [appnet]

  collabora:
    image: collabora/code
    container_name: collabora
    restart: unless-stopped
    volumes:
      - /srv/collabora/coolwsd:/etc/coolwsd
    environment:
      - aliasgroup1=https://nextcloud.home
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
      - DONT_GEN_SSL_CERT=true
      - username=admin
      - password=test
    networks: [appnet]
