services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8084
      - TORRENTING_PORT=6881
    volumes:
      - /srv/qbittorrent/appdata:/config
      - /srv/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
