#!/bin/sh
COMPOSE_DIR="/home-server"

usage() {
  echo "Usage: metis <up|down> <container name>"
  exit 1
}

[ $# -lt 2 ] && usage

COMMAND="$1"
SERVICE="$2"

case "$COMMAND" in
  up)   docker compose up -d "$SERVICE" ;;
  down) docker compose down "$SERVICE" ;;
  *)    usage ;;
esac
